#!/usr/bin/env php // Added for syntax coloration in file without extension .php
<?php
namespace App\Async;

require_once '../vendor/autoload.php';
require_once '../../../../wp-load.php';


use App\Async\AsyncTaskExecutor;
use App\Async\AsyncTasksGetter;


$recuperator = new AsyncTasksGetter();
$tasks = $recuperator->getTasksToExecute();

$executor = new AsyncTaskExecutor();

$results = [];
foreach ($tasks as $task) {
    $executor->setTask($task);
    $result = $executor->execute();
    $results[$task->id] = $result;
}

$recuperator->updateTasks($results);